language: python
python:
  - "3.6"
sudo: false
before_install:
  - make init
before_cache:
  - rm -rf $HOME/.cache/pip/log
cache:
  directories:
    - $HOME/.cache/pip
install: "pip install -r requirements.txt"
script: make run-tests-coverage
after_success:
  - codecov