site_url: https://www.instagram.com
username: discovrar
password: discorvd

posts:
  search_tags: films, movies
  ignore_tags: got, house, php
  posts_per_hashtag: 2
  likes_per_day: 100
  comment_enabled: true
  comment_generator: true
  custom_comments: []
  total_to_follow_per_hashtag: 1

followers:
  follow_enable: true
  min_followers: null
  max_followers: null
  ignore_users: []
  follow_per_day: 10
  ignore_friends: true
  unfollow_followed_users: true

pics:
  upload: true
  files:
    - path: '/home/santiago/projects/instagram/nn/sorted_pics/47__30_brussels.JPG'
      datetime: '2017-08-18 18:00'
      comment: '#awesome #belgium'
    - path: '/home/santiago/projects/instagram/nn/sorted_pics/48__20_santander_friends.JPG'
      datetime: '2017-08-19 19:10'

