username: discovrar
password: discorvd
hide_browser: false

posts:
  search_tags: []
  ignore_tags: []
  posts_per_hashtag: 20
  likes_per_day: 100
  like_probability: 0.5
  comments_per_day: 10
  comment_enabled: true
  comment_generator: true
  comment_probability: 0.5
  custom_comments: []
  total_to_follow_per_hashtag: 10

followers:
  follow_enable: true
  min_followers: 0
  max_followers: 0
  follow_probability: 0.5
  ignore_users: []
  follow_per_day: 50
  unfollow_followed_users: true

pics:
  upload: false
  files:
    - path: '/home/santiago/projects/instagram/nn/sorted_pics/47__30_brussels.JPG'
      datetime: '2016-08-18T18:00:00'
      description: '#awesome #belgium'
    - path: '/home/santiago/projects/instagram/nn/sorted_pics/48__20_santander_friends.JPG'
      datetime: '2016-08-19T19:10:00'
