username: discovrar
password: discorvd
hide_browser: false
testing: true

posts:
  search_tags: [apartmentdecor, architecture, building]
  ignore_tags: [
    hippie, parkour, freerunning, naturalskincare, streetart
    selfobsessed, ClassyGal, motivation,
    childrenphoto, handsome, thedubaimall, typography
  ]
  posts_per_hashtag: 2
  likes_per_day: 100
  like_probability: 0.5
  comments_per_day: 20
  comment_enabled: true
  comment_generator: true
  comment_probability: 0.5
  custom_comments: []
  total_to_follow_per_hashtag: 1

followers:
  follow_enable: true
  min_followers: null
  max_followers: null
  follow_probability: 0.5
  ignore_users: []
  follow_per_day: 50
  unfollow_followed_users: true

pics:
  upload: true
  files:
    - path: '/home/santiago/Pictures/one_day.jpg'
      datetime: '2017-08-31T13:30:00'
      description: '#motivation #getmotivated #phraseoftheday'
